/*
 * Parameter name to configuration field, for vesc.conf_get and
 * vesc.conf_set.
 *
 * GENERATED by tests/conf_table/gen_conf_table.py from the LispBM
 * extensions, which are the authoritative mapping. Do not edit by hand:
 * tests/conf_table/run.sh regenerates it and fails if this file differs,
 * so a hand edit is reported as a mismatch.
 *
 * Derived rather than retyped because a round-trip test cannot catch a
 * mis-mapping -- set-then-get agrees whether a name is wired to the
 * right field or the one next to it -- and a parameter silently reading
 * the wrong setting is the whole failure mode worth preventing here.
 *
 * X-macro lists naming the struct member, rather than a table of byte
 * offsets and widths. The field name lets the compiler choose the load,
 * which is the only way to get this right: uint8_t and uint16_t members
 * read four bytes wide are both unaligned and overlapping their
 * neighbours, and arm-none-eabi defaults to -fshort-enums, so an enum's
 * width cannot be known from the declaration either.
 *
 * The first argument is the parameter name as a bare identifier, so it
 * can be both stringified and pasted into an enumerator. That lets the
 * lists drive one name array and two switches instead of a strcmp chain
 * per operation -- six chains over 136 names compiled to 16 KB, which
 * was the third largest object in the firmware.
 *
 * Flags, both derived from the conf-set arm:
 *
 *   CONF_NEG_ABS  stored negative, given as a positive magnitude, which
 *                 is what lisp conf-set does (-fabsf). conf_get returns
 *                 the stored value either way, again matching lisp.
 *   CONF_APPLY    needs a full reconfigure rather than a write to the
 *                 live struct. Writing one of these through the fast
 *                 path leaves it looking set without taking effect.
 *
 * Seven parameters are absent because lisp scales or computes them
 * rather than reading a field: the five FOC motor constants and the two
 * speed limits. Those are written out in lua_vesc_conf.c.
 */

// clang-format off

#define CONF_MC_PARAMS(X) \
	X(bms_limit_mode, CONF_PLAIN, bms.limit_mode) \
	X(bms_t_limit_end, CONF_PLAIN, bms.t_limit_end) \
	X(bms_t_limit_start, CONF_PLAIN, bms.t_limit_start) \
	X(bms_vmax_limit_end, CONF_PLAIN, bms.vmax_limit_end) \
	X(bms_vmax_limit_start, CONF_PLAIN, bms.vmax_limit_start) \
	X(bms_vmin_limit_end, CONF_PLAIN, bms.vmin_limit_end) \
	X(bms_vmin_limit_start, CONF_PLAIN, bms.vmin_limit_start) \
	X(foc_current_ki, CONF_APPLY, foc_current_ki) \
	X(foc_current_kp, CONF_APPLY, foc_current_kp) \
	X(foc_encoder_inverted, CONF_PLAIN, foc_encoder_inverted) \
	X(foc_encoder_offset, CONF_PLAIN, foc_encoder_offset) \
	X(foc_encoder_ratio, CONF_PLAIN, foc_encoder_ratio) \
	X(foc_f_zv, CONF_APPLY, foc_f_zv) \
	X(foc_fw_backoff, CONF_APPLY, foc_fw_backoff) \
	X(foc_fw_current_max, CONF_APPLY, foc_fw_current_max) \
	X(foc_fw_duty_start, CONF_APPLY, foc_fw_duty_start) \
	X(foc_fw_q_current_factor, CONF_APPLY, foc_fw_q_current_factor) \
	X(foc_fw_ramp_time, CONF_APPLY, foc_fw_ramp_time) \
	X(foc_hall_t0, CONF_APPLY, foc_hall_table[0]) \
	X(foc_hall_t1, CONF_APPLY, foc_hall_table[1]) \
	X(foc_hall_t2, CONF_APPLY, foc_hall_table[2]) \
	X(foc_hall_t3, CONF_APPLY, foc_hall_table[3]) \
	X(foc_hall_t4, CONF_APPLY, foc_hall_table[4]) \
	X(foc_hall_t5, CONF_APPLY, foc_hall_table[5]) \
	X(foc_hall_t6, CONF_APPLY, foc_hall_table[6]) \
	X(foc_hall_t7, CONF_APPLY, foc_hall_table[7]) \
	X(foc_hfi_amb_current, CONF_APPLY, foc_hfi_amb_current) \
	X(foc_hfi_amb_mode, CONF_APPLY, foc_hfi_amb_mode) \
	X(foc_hfi_amb_tres, CONF_APPLY, foc_hfi_amb_tres) \
	X(foc_hfi_reset_erpm, CONF_APPLY, foc_hfi_reset_erpm) \
	X(foc_hfi_start_samples, CONF_APPLY, foc_hfi_start_samples) \
	X(foc_hfi_voltage_max, CONF_APPLY, foc_hfi_voltage_max) \
	X(foc_hfi_voltage_run, CONF_APPLY, foc_hfi_voltage_run) \
	X(foc_hfi_voltage_start, CONF_APPLY, foc_hfi_voltage_start) \
	X(foc_mag_vd_max, CONF_PLAIN, foc_mag_vd_max) \
	X(foc_mtpa_mode, CONF_APPLY, foc_mtpa_mode) \
	X(foc_observer_type, CONF_APPLY, foc_observer_type) \
	X(foc_offsets_cal_mode, CONF_PLAIN, foc_offsets_cal_mode) \
	X(foc_openloop_rpm, CONF_APPLY, foc_openloop_rpm) \
	X(foc_openloop_rpm_low, CONF_APPLY, foc_openloop_rpm_low) \
	X(foc_overmod_factor, CONF_PLAIN, foc_overmod_factor) \
	X(foc_sensor_mode, CONF_APPLY, foc_sensor_mode) \
	X(foc_short_ls_on_zero_duty, CONF_PLAIN, foc_short_ls_on_zero_duty) \
	X(foc_sl_erpm, CONF_APPLY, foc_sl_erpm) \
	X(foc_sl_erpm_hfi, CONF_APPLY, foc_sl_erpm_hfi) \
	X(foc_sl_erpm_start, CONF_APPLY, foc_sl_erpm_start) \
	X(foc_sl_openloop_time, CONF_APPLY, foc_sl_openloop_time) \
	X(foc_sl_openloop_time_lock, CONF_APPLY, foc_sl_openloop_time_lock) \
	X(foc_sl_openloop_time_ramp, CONF_APPLY, foc_sl_openloop_time_ramp) \
	X(foc_temp_comp, CONF_APPLY, foc_temp_comp) \
	X(foc_temp_comp_base_temp, CONF_APPLY, foc_temp_comp_base_temp) \
	X(l_abs_current_max, CONF_PLAIN, l_abs_current_max) \
	X(l_battery_cut_end, CONF_PLAIN, l_battery_cut_end) \
	X(l_battery_cut_start, CONF_PLAIN, l_battery_cut_start) \
	X(l_current_max, CONF_PLAIN, l_current_max) \
	X(l_current_max_scale, CONF_PLAIN, l_current_max_scale) \
	X(l_current_min, CONF_NEG_ABS, l_current_min) \
	X(l_current_min_scale, CONF_PLAIN, l_current_min_scale) \
	X(l_erpm_start, CONF_PLAIN, l_erpm_start) \
	X(l_in_current_max, CONF_PLAIN, l_in_current_max) \
	X(l_in_current_min, CONF_NEG_ABS, l_in_current_min) \
	X(l_max_duty, CONF_PLAIN, l_max_duty) \
	X(l_max_erpm, CONF_PLAIN, l_max_erpm) \
	X(l_max_vin, CONF_PLAIN, l_max_vin) \
	X(l_min_duty, CONF_PLAIN, l_min_duty) \
	X(l_min_erpm, CONF_NEG_ABS, l_min_erpm) \
	X(l_min_vin, CONF_PLAIN, l_min_vin) \
	X(l_temp_accel_dec, CONF_PLAIN, l_temp_accel_dec) \
	X(l_temp_motor_end, CONF_PLAIN, l_temp_motor_end) \
	X(l_temp_motor_start, CONF_PLAIN, l_temp_motor_start) \
	X(l_watt_max, CONF_PLAIN, l_watt_max) \
	X(l_watt_min, CONF_NEG_ABS, l_watt_min) \
	X(m_encoder_counts, CONF_APPLY, m_encoder_counts) \
	X(m_fault_stop_time_ms, CONF_PLAIN, m_fault_stop_time_ms) \
	X(m_invert_direction, CONF_PLAIN, m_invert_direction) \
	X(m_motor_temp_sens_type, CONF_PLAIN, m_motor_temp_sens_type) \
	X(m_ntc_motor_beta, CONF_PLAIN, m_ntc_motor_beta) \
	X(m_ntcx_ptcx_res, CONF_PLAIN, m_ntcx_ptcx_res) \
	X(m_ntcx_ptcx_temp_base, CONF_PLAIN, m_ntcx_ptcx_temp_base) \
	X(m_out_aux_mode, CONF_PLAIN, m_out_aux_mode) \
	X(m_ptc_motor_coeff, CONF_PLAIN, m_ptc_motor_coeff) \
	X(m_sensor_port_mode, CONF_APPLY, m_sensor_port_mode) \
	X(motor_type, CONF_APPLY, motor_type) \
	X(si_battery_ah, CONF_PLAIN, si_battery_ah) \
	X(si_battery_cells, CONF_PLAIN, si_battery_cells) \
	X(si_gear_ratio, CONF_PLAIN, si_gear_ratio) \
	X(si_motor_poles, CONF_PLAIN, si_motor_poles) \
	X(si_wheel_diameter, CONF_PLAIN, si_wheel_diameter) \
	/* end */

#define CONF_APP_PARAMS(X) \
	X(adc_coast_brake_level, CONF_APPLY, app_adc_conf.coast_brake_level) \
	X(adc_coast_brake_ramp_time, CONF_APPLY, app_adc_conf.coast_brake_ramp_time) \
	X(adc_ctrl_type, CONF_APPLY, app_adc_conf.ctrl_type) \
	X(adc_ramp_time_neg, CONF_APPLY, app_adc_conf.ramp_time_neg) \
	X(adc_ramp_time_pos, CONF_APPLY, app_adc_conf.ramp_time_pos) \
	X(adc_tc, CONF_APPLY, app_adc_conf.tc) \
	X(adc_tc_max_diff, CONF_APPLY, app_adc_conf.tc_max_diff) \
	X(adc_thr_hyst, CONF_APPLY, app_adc_conf.hyst) \
	X(adc_v1_center, CONF_APPLY, app_adc_conf.voltage_center) \
	X(adc_v1_end, CONF_APPLY, app_adc_conf.voltage_end) \
	X(adc_v1_max, CONF_APPLY, app_adc_conf.voltage_max) \
	X(adc_v1_min, CONF_APPLY, app_adc_conf.voltage_min) \
	X(adc_v1_start, CONF_APPLY, app_adc_conf.voltage_start) \
	X(adc_v2_end, CONF_APPLY, app_adc_conf.voltage2_end) \
	X(adc_v2_start, CONF_APPLY, app_adc_conf.voltage2_start) \
	X(app_to_use, CONF_APPLY, app_to_use) \
	X(can_baud_rate, CONF_APPLY, can_baud_rate) \
	X(can_mode, CONF_APPLY, can_mode) \
	X(can_status_msgs_r1, CONF_PLAIN, can_status_msgs_r1) \
	X(can_status_msgs_r2, CONF_PLAIN, can_status_msgs_r2) \
	X(can_status_rate_1, CONF_PLAIN, can_status_rate_1) \
	X(can_status_rate_2, CONF_PLAIN, can_status_rate_2) \
	X(controller_id, CONF_PLAIN, controller_id) \
	X(pas_assist_gain, CONF_APPLY, app_pas_conf.assist_gain) \
	X(pas_ctrl_type, CONF_APPLY, app_pas_conf.ctrl_type) \
	X(pas_current_scaling, CONF_APPLY, app_pas_conf.current_scaling) \
	X(pas_magnets, CONF_APPLY, app_pas_conf.magnets) \
	X(pas_power_max_w, CONF_APPLY, app_pas_conf.power_max_w) \
	X(pas_start_timeout_s, CONF_APPLY, app_pas_conf.start_timeout_s) \
	X(pas_stop_timeout_s, CONF_APPLY, app_pas_conf.stop_timeout_s) \
	X(pas_taper_end_kmh, CONF_APPLY, app_pas_conf.taper_end_kmh) \
	X(pas_taper_start_kmh, CONF_APPLY, app_pas_conf.taper_start_kmh) \
	X(pas_torque_nm_per_v, CONF_APPLY, app_pas_conf.torque_nm_per_v) \
	X(pas_torque_zero_v, CONF_APPLY, app_pas_conf.torque_zero_v) \
	X(ppm_ctrl_type, CONF_APPLY, app_ppm_conf.ctrl_type) \
	X(ppm_hyst, CONF_APPLY, app_ppm_conf.hyst) \
	X(ppm_pulse_center, CONF_APPLY, app_ppm_conf.pulse_center) \
	X(ppm_pulse_end, CONF_APPLY, app_ppm_conf.pulse_end) \
	X(ppm_pulse_start, CONF_APPLY, app_ppm_conf.pulse_start) \
	X(ppm_ramp_time_neg, CONF_APPLY, app_ppm_conf.ramp_time_neg) \
	X(ppm_ramp_time_pos, CONF_APPLY, app_ppm_conf.ramp_time_pos) \
	X(timeout_msec, CONF_PLAIN, timeout_msec) \
	X(vr_cc_erpm_per_s, CONF_APPLY, app_chuk_conf.stick_erpm_per_s_in_cc) \
	X(vr_coast_brake_level, CONF_APPLY, app_chuk_conf.coast_brake_level) \
	X(vr_coast_brake_ramp_time, CONF_APPLY, app_chuk_conf.coast_brake_ramp_time) \
	X(vr_ctrl_type, CONF_APPLY, app_chuk_conf.ctrl_type) \
	X(vr_hyst, CONF_APPLY, app_chuk_conf.hyst) \
	X(vr_multi_esc, CONF_APPLY, app_chuk_conf.multi_esc) \
	X(vr_ramp_time_neg, CONF_APPLY, app_chuk_conf.ramp_time_neg) \
	X(vr_ramp_time_pos, CONF_APPLY, app_chuk_conf.ramp_time_pos) \
	X(vr_smart_rev_max_duty, CONF_APPLY, app_chuk_conf.smart_rev_max_duty) \
	X(vr_smart_rev_ramp_time, CONF_APPLY, app_chuk_conf.smart_rev_ramp_time) \
	X(vr_tc, CONF_APPLY, app_chuk_conf.tc) \
	X(vr_tc_max_diff, CONF_APPLY, app_chuk_conf.tc_max_diff) \
	X(vr_throttle_exp, CONF_APPLY, app_chuk_conf.throttle_exp) \
	X(vr_throttle_exp_brake, CONF_APPLY, app_chuk_conf.throttle_exp_brake) \
	X(vr_throttle_exp_mode, CONF_APPLY, app_chuk_conf.throttle_exp_mode) \
	X(vr_use_smart_rev, CONF_APPLY, app_chuk_conf.use_smart_rev) \
	/* end */

#define CONF_MC_PARAM_COUNT 88
#define CONF_APP_PARAM_COUNT 58

// clang-format on
